[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
ffi = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
solc = "0.8.22"

[rpc_endpoints]
minato = "https://rpc.minato.soneium.org"